#!/usr/bin/bash

# Make sure everything is up-to-date
apt update
apt -o Dpkg::Options::='--force-confold' -y upgrade

cd KioskWeb

git pull origin

chmod +x start
chmod +x get-login

mv start ~
mv get-login ~

npm i

npm run build

npm start