#!/bin/bash

# Install base packages
apt update
apt -o Dpkg::Options::='--force-confold' -y upgrade # force-confold makes it so no config files are changed

# Install nessasary packages to run kiosk
apt -y install nodejs
apt -y install openssh # Openssh will allow filezilla to connect to kiosk
apt -y install termux-auth # Makes passwd available for termux
apt -y install firefox-esr # Firefox is needed for a better scroll

npm i n --global
sudo n i lts

# Make other scripts runnable
chmod +x start
chmod +x get-login
# Move start script and other useful scripts to home directory
mkdir ../../Desktop

cp start ../../Desktop
cp get-login ../../Desktop

cp start ../../
cp get-login ../../
# Make shortcut to images folder on home directory
ln -s ~/KioskWeb/public/images ~/images
# add current directory (.) to PATH variable so they can just type start instead of ./start
echo "PATH=.:$PATH;export PATH" >> ~/.bashrc

# Start openssh
sshd
# Display kiosk ip and username, and prompt password that will be used for Filezilla
~/get-login

# No more password input as it's handled by the os now
# passwd


echo "Setup complete!"

# Start a new bash session that replaces the old one so they 
# can immediately start using the new .bashrc
# Doing so also appears to move to the user's home directory.
# This MUST be at the last command executed.
# exec bash 
