#!/usr/bin/bash

# Make sure everything is up-to-date
apt update
apt -o Dpkg::Options::='--force-confold' -y upgrade

cd KioskWeb

git pull origin

chmod +x scripts/start
chmod +x scripts/get-login

mv scripts/start ~
mv scripts/get-login ~

npm i

npm run build

npm start