#!/bin/bash

# Make sure everything is up-to-date
# probably don't do this
# apt update
# apt -o Dpkg::Options::='--force-confold' -y upgrade

# If one doesn't work than the other one should.
cd ../KioskWeb
cd KioskWeb

git pull origin main

chmod +x scripts/start
chmod +x scripts/get-login

cp scripts/start ../Desktop
cp scripts/get-login ../Desktop

cp scripts/start ../
cp scripts/get-login ../

npm i

npm run build

npm start