#!/bin/bash

# Make sure everything is up-to-date
# probably don't do this
# apt update
# apt -o Dpkg::Options::='--force-confold' -y upgrade

cd KioskWeb

git pull origin

chmod +x scripts/start
chmod +x scripts/get-login

mv scripts/start ../Desktop
mv scripts/get-login ../Desktop

npm i

npm run build

npm start